implement bond reflect, diene rotate

diff --git a/check/check b/check/check
--- a/check/check
+++ b/check/check
@@ -7,15 +7,16 @@ ORIENT=$BASE/../orient.py
 
 # general test
 $ORIENT -tx 1.0 -ty -0.7 -tz 0.2 -rx 75 -ry 40 -rz -60 $BASE/test.xyz > $BASE/general/output.xyz
-DIFF=$(diff -b $BASE/general/output.xyz $BASE/general/reference.xyz)
+DIFF=$(diff -b $BASE/general/output.xyz $BASE/general/reference.xyz 2>&1)
 if [ "$DIFF" != "" ]; then
+  echo $?
   echo 'General test failed!'
   let nfailed+=1
 fi
 
 # principle axes test
 $ORIENT -op $BASE/test.xyz > $BASE/principle/output.xyz
-DIFF=$(diff -b $BASE/principle/output.xyz $BASE/principle/reference.xyz)
+DIFF=$(diff -b $BASE/principle/output.xyz $BASE/principle/reference.xyz 2>&1)
 if [ "$DIFF" != "" ]; then
   echo 'Principle test failed!'
   let nfailed+=1
@@ -23,7 +24,7 @@ fi
 
 # align test
 $ORIENT -a 1 2 3 $BASE/test.xyz > $BASE/align/output.xyz
-DIFF=$(diff -b $BASE/align/output.xyz $BASE/align/reference.xyz)
+DIFF=$(diff -b $BASE/align/output.xyz $BASE/align/reference.xyz 2>&1)
 if [ "$DIFF" != "" ]; then
   echo 'Align test failed!'
   let nfailed+=1
@@ -31,15 +32,15 @@ fi
 
 # fitplane test
 $ORIENT -p 1 12 2 3 $BASE/test.xyz > $BASE/fitplane/output.xyz
-DIFF=$(diff -b $BASE/fitplane/output.xyz $BASE/fitplane/reference.xyz)
+DIFF=$(diff -b $BASE/fitplane/output.xyz $BASE/fitplane/reference.xyz 2>&1)
 if [ "$DIFF" != "" ]; then
   echo 'fitplane test failed!'
   let nfailed+=1
 fi
 
 # rotatepair test
-$ORIENT -rp 17 18 180 $BASE/test.xyz > $BASE/rotatepair/output.xyz
-DIFF=$(diff -b $BASE/rotatepair/output.xyz $BASE/rotatepair/reference.xyz)
+$ORIENT -rb 180 17 18 $BASE/test.xyz > $BASE/rotatepair/output.xyz
+DIFF=$(diff -b $BASE/rotatepair/output.xyz $BASE/rotatepair/reference.xyz 2>&1)
 if [ "$DIFF" != "" ]; then
   echo 'rotatepair test failed!'
   let nfailed+=1
@@ -47,9 +48,25 @@ fi
 
 # reflectplane test
 $ORIENT -sp 2 3 4 12 $BASE/test.xyz > $BASE/reflectplane/output.xyz
-DIFF=$(diff -b $BASE/reflectplane/output.xyz $BASE/reflectplane/reference.xyz)
+DIFF=$(diff -b $BASE/reflectplane/output.xyz $BASE/reflectplane/reference.xyz 2>&1)
 if [ "$DIFF" != "" ]; then
   echo 'reflectplane test failed!'
+  let nfailed+=1
+fi
+
+# bond reflect test
+$ORIENT -sb 12 13 $BASE/5vu.xyz > $BASE/bondreflect/output.xyz
+DIFF=$(diff -b $BASE/bondreflect/output.xyz $BASE/bondreflect/reference.xyz 2>&1)
+if [ "$DIFF" != "" ]; then
+  echo 'bondreflect test failed!'
+  let nfailed+=1
+fi
+
+# diene test
+$ORIENT -rd 90 12 13 14 $BASE/5vu.xyz > $BASE/diene/output.xyz
+DIFF=$(diff -b $BASE/diene/output.xyz $BASE/diene/reference.xyz 2>&1)
+if [ "$DIFF" != "" ]; then
+  echo 'diene test failed!'
   let nfailed+=1
 fi
 
